name: Build, Package and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 

    - name: Extract version tag
      run: echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Log in to GHCR using a PAT
      uses: docker/login-action@v2  
      with:
        registry: ghcr.io
        username: ${{ github.actor }} 
        password: ${{ secrets.GITHUB_TOKEN }} 

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./docker
        push: true  
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.sha }}
          ghcr.io/${{ github.repository }}:${{ env.VERSION_TAG }}
          ghcr.io/${{ github.repository }}:latest

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION_TAG }}
        draft: false
        prerelease: false